using UnityEngine;
using System;

// xkcd.com/color/rgb
public static class CommonColor
{
	internal class ColorTranslator
	{
		public static Color FromHTML(string hexString)
		{
			return new Color(Convert.ToInt32(hexString.Substring(1, 2), 16) / 255f,
				Convert.ToInt32(hexString.Substring(3, 2), 16) / 255f,
				Convert.ToInt32(hexString.Substring(5, 2), 16) / 255f);
		}
	}

	public static Color CloudyBlue { get { return ColorTranslator.FromHTML("#acc2d9"); } }
	public static Color DarkPastelGreen { get { return ColorTranslator.FromHTML("#56ae57"); } }
	public static Color Dust { get { return ColorTranslator.FromHTML("#b2996e"); } }
	public static Color ElectricLime { get { return ColorTranslator.FromHTML("#a8ff04"); } }
	public static Color FreshGreen { get { return ColorTranslator.FromHTML("#69d84f"); } }
	public static Color LightEggplant { get { return ColorTranslator.FromHTML("#894585"); } }
	public static Color NastyGreen { get { return ColorTranslator.FromHTML("#70b23f"); } }
	public static Color ReallyLightBlue { get { return ColorTranslator.FromHTML("#d4ffff"); } }
	public static Color Tea { get { return ColorTranslator.FromHTML("#65ab7c"); } }
	public static Color WarmPurple { get { return ColorTranslator.FromHTML("#952e8f"); } }
	public static Color YellowishTan { get { return ColorTranslator.FromHTML("#fcfc81"); } }
	public static Color Cement { get { return ColorTranslator.FromHTML("#a5a391"); } }
	public static Color DarkGrassGreen { get { return ColorTranslator.FromHTML("#388004"); } }
	public static Color DustyTeal { get { return ColorTranslator.FromHTML("#4c9085"); } }
	public static Color GreyTeal { get { return ColorTranslator.FromHTML("#5e9b8a"); } }
	public static Color MacaroniAndCheese { get { return ColorTranslator.FromHTML("#efb435"); } }
	public static Color PinkishTan { get { return ColorTranslator.FromHTML("#d99b82"); } }
	public static Color Spruce { get { return ColorTranslator.FromHTML("#0a5f38"); } }
	public static Color StrongBlue { get { return ColorTranslator.FromHTML("#0c06f7"); } }
	public static Color ToxicGreen { get { return ColorTranslator.FromHTML("#61de2a"); } }
	public static Color WindowsBlue { get { return ColorTranslator.FromHTML("#3778bf"); } }
	public static Color BlueBlue { get { return ColorTranslator.FromHTML("#2242c7"); } }
	public static Color BlueWithAHintOfPurple { get { return ColorTranslator.FromHTML("#533cc6"); } }
	public static Color Booger { get { return ColorTranslator.FromHTML("#9bb53c"); } }
	public static Color BrightSeaGreen { get { return ColorTranslator.FromHTML("#05ffa6"); } }
	public static Color DarkGreenBlue { get { return ColorTranslator.FromHTML("#1f6357"); } }
	public static Color DeepTurquoise { get { return ColorTranslator.FromHTML("#017374"); } }
	public static Color GreenTeal { get { return ColorTranslator.FromHTML("#0cb577"); } }
	public static Color StrongPink { get { return ColorTranslator.FromHTML("#ff0789"); } }
	public static Color Bland { get { return ColorTranslator.FromHTML("#afa88b"); } }
	public static Color DeepAqua { get { return ColorTranslator.FromHTML("#08787f"); } }
	public static Color LavenderPink { get { return ColorTranslator.FromHTML("#dd85d7"); } }
	public static Color LightMossGreen { get { return ColorTranslator.FromHTML("#a6c875"); } }
	public static Color LightSeafoamGreen { get { return ColorTranslator.FromHTML("#a7ffb5"); } }
	public static Color OliveYellow { get { return ColorTranslator.FromHTML("#c2b709"); } }
	public static Color PigPink { get { return ColorTranslator.FromHTML("#e78ea5"); } }
	public static Color DeepLilac { get { return ColorTranslator.FromHTML("#966ebd"); } }
	public static Color Desert { get { return ColorTranslator.FromHTML("#ccad60"); } }
	public static Color DustyLavender { get { return ColorTranslator.FromHTML("#ac86a8"); } }
	public static Color PurpleyGrey { get { return ColorTranslator.FromHTML("#947e94"); } }
	public static Color Purply { get { return ColorTranslator.FromHTML("#983fb2"); } }
	public static Color CandyPink { get { return ColorTranslator.FromHTML("#ff63e9"); } }
	public static Color LightPastelGreen { get { return ColorTranslator.FromHTML("#b2fba5"); } }
	public static Color BoringGreen { get { return ColorTranslator.FromHTML("#63b365"); } }
	public static Color KiwiGreen { get { return ColorTranslator.FromHTML("#8ee53f"); } }
	public static Color LightGreyGreen { get { return ColorTranslator.FromHTML("#b7e1a1"); } }
	public static Color OrangePink { get { return ColorTranslator.FromHTML("#ff6f52"); } }
	public static Color TeaGreen { get { return ColorTranslator.FromHTML("#bdf8a3"); } }
	public static Color VeryLightBrown { get { return ColorTranslator.FromHTML("#d3b683"); } }
	public static Color EggShell { get { return ColorTranslator.FromHTML("#fffcc4"); } }
	public static Color EggplantPurple { get { return ColorTranslator.FromHTML("#430541"); } }
	public static Color PowderPink { get { return ColorTranslator.FromHTML("#ffb2d0"); } }
	public static Color ReddishGrey { get { return ColorTranslator.FromHTML("#997570"); } }
	public static Color BabyShitBrown { get { return ColorTranslator.FromHTML("#ad900d"); } }
	public static Color Liliac { get { return ColorTranslator.FromHTML("#c48efd"); } }
	public static Color StormyBlue { get { return ColorTranslator.FromHTML("#507b9c"); } }
	public static Color UglyBrown { get { return ColorTranslator.FromHTML("#7d7103"); } }
	public static Color Custard { get { return ColorTranslator.FromHTML("#fffd78"); } }
	public static Color DarkishPink { get { return ColorTranslator.FromHTML("#da467d"); } }
	public static Color DeepBrown { get { return ColorTranslator.FromHTML("#410200"); } }
	public static Color GreenishBeige { get { return ColorTranslator.FromHTML("#c9d179"); } }
	public static Color Manilla { get { return ColorTranslator.FromHTML("#fffa86"); } }
	public static Color OffBlue { get { return ColorTranslator.FromHTML("#5684ae"); } }
	public static Color BattleshipGrey { get { return ColorTranslator.FromHTML("#6b7c85"); } }
	public static Color BrownyGreen { get { return ColorTranslator.FromHTML("#6f6c0a"); } }
	public static Color Bruise { get { return ColorTranslator.FromHTML("#7e4071"); } }
	public static Color KelleyGreen { get { return ColorTranslator.FromHTML("#009337"); } }
	public static Color SicklyYellow { get { return ColorTranslator.FromHTML("#d0e429"); } }
	public static Color SunnyYellow { get { return ColorTranslator.FromHTML("#fff917"); } }
	public static Color Azul { get { return ColorTranslator.FromHTML("#1d5dec"); } }
	public static Color Darkgreen { get { return ColorTranslator.FromHTML("#054907"); } }
	public static Color Green_Yellow { get { return ColorTranslator.FromHTML("#b5ce08"); } }
	public static Color Lichen { get { return ColorTranslator.FromHTML("#8fb67b"); } }
	public static Color LightLightGreen { get { return ColorTranslator.FromHTML("#c8ffb0"); } }
	public static Color PaleGold { get { return ColorTranslator.FromHTML("#fdde6c"); } }
	public static Color SunYellow { get { return ColorTranslator.FromHTML("#ffdf22"); } }
	public static Color TanGreen { get { return ColorTranslator.FromHTML("#a9be70"); } }
	public static Color Burple { get { return ColorTranslator.FromHTML("#6832e3"); } }
	public static Color Butterscotch { get { return ColorTranslator.FromHTML("#fdb147"); } }
	public static Color Toupe { get { return ColorTranslator.FromHTML("#c7ac7d"); } }
	public static Color DarkCream { get { return ColorTranslator.FromHTML("#fff39a"); } }
	public static Color IndianRed { get { return ColorTranslator.FromHTML("#850e04"); } }
	public static Color LightLavendar { get { return ColorTranslator.FromHTML("#efc0fe"); } }
	public static Color PoisonGreen { get { return ColorTranslator.FromHTML("#40fd14"); } }
	public static Color BabyPukeGreen { get { return ColorTranslator.FromHTML("#b6c406"); } }
	public static Color BrightYellowGreen { get { return ColorTranslator.FromHTML("#9dff00"); } }
	public static Color CharcoalGrey { get { return ColorTranslator.FromHTML("#3c4142"); } }
	public static Color Squash { get { return ColorTranslator.FromHTML("#f2ab15"); } }
	public static Color Cinnamon { get { return ColorTranslator.FromHTML("#ac4f06"); } }
	public static Color LightPeaGreen { get { return ColorTranslator.FromHTML("#c4fe82"); } }
	public static Color RadioactiveGreen { get { return ColorTranslator.FromHTML("#2cfa1f"); } }
	public static Color RawSienna { get { return ColorTranslator.FromHTML("#9a6200"); } }
	public static Color BabyPurple { get { return ColorTranslator.FromHTML("#ca9bf7"); } }
	public static Color Cocoa { get { return ColorTranslator.FromHTML("#875f42"); } }
	public static Color LightRoyalBlue { get { return ColorTranslator.FromHTML("#3a2efe"); } }
	public static Color Orangeish { get { return ColorTranslator.FromHTML("#fd8d49"); } }
	public static Color RustBrown { get { return ColorTranslator.FromHTML("#8b3103"); } }
	public static Color SandBrown { get { return ColorTranslator.FromHTML("#cba560"); } }
	public static Color Swamp { get { return ColorTranslator.FromHTML("#698339"); } }
	public static Color TealishGreen { get { return ColorTranslator.FromHTML("#0cdc73"); } }
	public static Color BurntSiena { get { return ColorTranslator.FromHTML("#b75203"); } }
	public static Color Camo { get { return ColorTranslator.FromHTML("#7f8f4e"); } }
	public static Color DuskBlue { get { return ColorTranslator.FromHTML("#26538d"); } }
	public static Color Fern { get { return ColorTranslator.FromHTML("#63a950"); } }
	public static Color OldRose { get { return ColorTranslator.FromHTML("#c87f89"); } }
	public static Color PaleLightGreen { get { return ColorTranslator.FromHTML("#b1fc99"); } }
	public static Color PeachyPink { get { return ColorTranslator.FromHTML("#ff9a8a"); } }
	public static Color RosyPink { get { return ColorTranslator.FromHTML("#f6688e"); } }
	public static Color LightBluishGreen { get { return ColorTranslator.FromHTML("#76fda8"); } }
	public static Color LightBrightGreen { get { return ColorTranslator.FromHTML("#53fe5c"); } }
	public static Color LightNeonGreen { get { return ColorTranslator.FromHTML("#4efd54"); } }
	public static Color LightSeafoam { get { return ColorTranslator.FromHTML("#a0febf"); } }
	public static Color TiffanyBlue { get { return ColorTranslator.FromHTML("#7bf2da"); } }
	public static Color WashedOutGreen { get { return ColorTranslator.FromHTML("#bcf5a6"); } }
	public static Color BrownyOrange { get { return ColorTranslator.FromHTML("#ca6b02"); } }
	public static Color NiceBlue { get { return ColorTranslator.FromHTML("#107ab0"); } }
	public static Color Sapphire { get { return ColorTranslator.FromHTML("#2138ab"); } }
	public static Color GreyishTeal { get { return ColorTranslator.FromHTML("#719f91"); } }
	public static Color OrangeyYellow { get { return ColorTranslator.FromHTML("#fdb915"); } }
	public static Color Parchment { get { return ColorTranslator.FromHTML("#fefcaf"); } }
	public static Color Straw { get { return ColorTranslator.FromHTML("#fcf679"); } }
	public static Color VeryDarkBrown { get { return ColorTranslator.FromHTML("#1d0200"); } }
	public static Color Terracota { get { return ColorTranslator.FromHTML("#cb6843"); } }
	public static Color UglyBlue { get { return ColorTranslator.FromHTML("#31668a"); } }
	public static Color ClearBlue { get { return ColorTranslator.FromHTML("#247afd"); } }
	public static Color Creme { get { return ColorTranslator.FromHTML("#ffffb6"); } }
	public static Color FoamGreen { get { return ColorTranslator.FromHTML("#90fda9"); } }
	public static Color Grey_Green { get { return ColorTranslator.FromHTML("#86a17d"); } }
	public static Color LightGold { get { return ColorTranslator.FromHTML("#fddc5c"); } }
	public static Color SeafoamBlue { get { return ColorTranslator.FromHTML("#78d1b6"); } }
	public static Color Topaz { get { return ColorTranslator.FromHTML("#13bbaf"); } }
	public static Color VioletPink { get { return ColorTranslator.FromHTML("#fb5ffc"); } }
	public static Color Wintergreen { get { return ColorTranslator.FromHTML("#20f986"); } }
	public static Color YellowTan { get { return ColorTranslator.FromHTML("#ffe36e"); } }
	public static Color DarkFuchsia { get { return ColorTranslator.FromHTML("#9d0759"); } }
	public static Color IndigoBlue { get { return ColorTranslator.FromHTML("#3a18b1"); } }
	public static Color LightYellowishGreen { get { return ColorTranslator.FromHTML("#c2ff89"); } }
	public static Color PaleMagenta { get { return ColorTranslator.FromHTML("#d767ad"); } }
	public static Color RichPurple { get { return ColorTranslator.FromHTML("#720058"); } }
	public static Color SunflowerYellow { get { return ColorTranslator.FromHTML("#ffda03"); } }
	public static Color Green_Blue { get { return ColorTranslator.FromHTML("#01c08d"); } }
	public static Color Leather { get { return ColorTranslator.FromHTML("#ac7434"); } }
	public static Color RacingGreen { get { return ColorTranslator.FromHTML("#014600"); } }
	public static Color VividPurple { get { return ColorTranslator.FromHTML("#9900fa"); } }
	public static Color DarkRoyalBlue { get { return ColorTranslator.FromHTML("#02066f"); } }
	public static Color Hazel { get { return ColorTranslator.FromHTML("#8e7618"); } }
	public static Color MutedPink { get { return ColorTranslator.FromHTML("#d1768f"); } }
	public static Color BoogerGreen { get { return ColorTranslator.FromHTML("#96b403"); } }
	public static Color Canary { get { return ColorTranslator.FromHTML("#fdff63"); } }
	public static Color CoolGrey { get { return ColorTranslator.FromHTML("#95a3a6"); } }
	public static Color DarkTaupe { get { return ColorTranslator.FromHTML("#7f684e"); } }
	public static Color DarkishPurple { get { return ColorTranslator.FromHTML("#751973"); } }
	public static Color TrueGreen { get { return ColorTranslator.FromHTML("#089404"); } }
	public static Color CoralPink { get { return ColorTranslator.FromHTML("#ff6163"); } }
	public static Color DarkSage { get { return ColorTranslator.FromHTML("#598556"); } }
	public static Color DarkSlateBlue { get { return ColorTranslator.FromHTML("#214761"); } }
	public static Color FlatBlue { get { return ColorTranslator.FromHTML("#3c73a8"); } }
	public static Color Mushroom { get { return ColorTranslator.FromHTML("#ba9e88"); } }
	public static Color RichBlue { get { return ColorTranslator.FromHTML("#021bf9"); } }
	public static Color DirtyPurple { get { return ColorTranslator.FromHTML("#734a65"); } }
	public static Color Greenblue { get { return ColorTranslator.FromHTML("#23c48b"); } }
	public static Color IckyGreen { get { return ColorTranslator.FromHTML("#8fae22"); } }
	public static Color LightKhaki { get { return ColorTranslator.FromHTML("#e6f2a2"); } }
	public static Color WarmBlue { get { return ColorTranslator.FromHTML("#4b57db"); } }
	public static Color DarkHotPink { get { return ColorTranslator.FromHTML("#d90166"); } }
	public static Color DeepSeaBlue { get { return ColorTranslator.FromHTML("#015482"); } }
	public static Color Carmine { get { return ColorTranslator.FromHTML("#9d0216"); } }
	public static Color DarkYellowGreen { get { return ColorTranslator.FromHTML("#728f02"); } }
	public static Color PalePeach { get { return ColorTranslator.FromHTML("#ffe5ad"); } }
	public static Color PlumPurple { get { return ColorTranslator.FromHTML("#4e0550"); } }
	public static Color GoldenRod { get { return ColorTranslator.FromHTML("#f9bc08"); } }
	public static Color NeonRed { get { return ColorTranslator.FromHTML("#ff073a"); } }
	public static Color OldPink { get { return ColorTranslator.FromHTML("#c77986"); } }
	public static Color VeryPaleBlue { get { return ColorTranslator.FromHTML("#d6fffe"); } }
	public static Color BloodOrange { get { return ColorTranslator.FromHTML("#fe4b03"); } }
	public static Color Grapefruit { get { return ColorTranslator.FromHTML("#fd5956"); } }
	public static Color SandYellow { get { return ColorTranslator.FromHTML("#fce166"); } }
	public static Color ClayBrown { get { return ColorTranslator.FromHTML("#b2713d"); } }
	public static Color DarkBlueGrey { get { return ColorTranslator.FromHTML("#1f3b4d"); } }
	public static Color FlatGreen { get { return ColorTranslator.FromHTML("#699d4c"); } }
	public static Color LightGreenBlue { get { return ColorTranslator.FromHTML("#56fca2"); } }
	public static Color WarmPink { get { return ColorTranslator.FromHTML("#fb5581"); } }
	public static Color DodgerBlue { get { return ColorTranslator.FromHTML("#3e82fc"); } }
	public static Color GrossGreen { get { return ColorTranslator.FromHTML("#a0bf16"); } }
	public static Color Ice { get { return ColorTranslator.FromHTML("#d6fffa"); } }
	public static Color MetallicBlue { get { return ColorTranslator.FromHTML("#4f738e"); } }
	public static Color PaleSalmon { get { return ColorTranslator.FromHTML("#ffb19a"); } }
	public static Color SapGreen { get { return ColorTranslator.FromHTML("#5c8b15"); } }
	public static Color Algae { get { return ColorTranslator.FromHTML("#54ac68"); } }
	public static Color BlueyGrey { get { return ColorTranslator.FromHTML("#89a0b0"); } }
	public static Color GreenyGrey { get { return ColorTranslator.FromHTML("#7ea07a"); } }
	public static Color HighlighterGreen { get { return ColorTranslator.FromHTML("#1bfc06"); } }
	public static Color LightLightBlue { get { return ColorTranslator.FromHTML("#cafffb"); } }
	public static Color LightMint { get { return ColorTranslator.FromHTML("#b6ffbb"); } }
	public static Color RawUmber { get { return ColorTranslator.FromHTML("#a75e09"); } }
	public static Color VividBlue { get { return ColorTranslator.FromHTML("#152eff"); } }
	public static Color DeepLavender { get { return ColorTranslator.FromHTML("#8d5eb7"); } }
	public static Color DullTeal { get { return ColorTranslator.FromHTML("#5f9e8f"); } }
	public static Color LightGreenishBlue { get { return ColorTranslator.FromHTML("#63f7b4"); } }
	public static Color MudGreen { get { return ColorTranslator.FromHTML("#606602"); } }
	public static Color Pinky { get { return ColorTranslator.FromHTML("#fc86aa"); } }
	public static Color RedWine { get { return ColorTranslator.FromHTML("#8c0034"); } }
	public static Color ShitGreen { get { return ColorTranslator.FromHTML("#758000"); } }
	public static Color TanBrown { get { return ColorTranslator.FromHTML("#ab7e4c"); } }
	public static Color Darkblue { get { return ColorTranslator.FromHTML("#030764"); } }
	public static Color Rosa { get { return ColorTranslator.FromHTML("#fe86a4"); } }
	public static Color Lipstick { get { return ColorTranslator.FromHTML("#d5174e"); } }
	public static Color PaleMauve { get { return ColorTranslator.FromHTML("#fed0fc"); } }
	public static Color Claret { get { return ColorTranslator.FromHTML("#680018"); } }
	public static Color Dandelion { get { return ColorTranslator.FromHTML("#fedf08"); } }
	public static Color Orangered { get { return ColorTranslator.FromHTML("#fe420f"); } }
	public static Color PoopGreen { get { return ColorTranslator.FromHTML("#6f7c00"); } }
	public static Color Ruby { get { return ColorTranslator.FromHTML("#ca0147"); } }
	public static Color Dark { get { return ColorTranslator.FromHTML("#1b2431"); } }
	public static Color GreenishTurquoise { get { return ColorTranslator.FromHTML("#00fbb0"); } }
	public static Color PastelRed { get { return ColorTranslator.FromHTML("#db5856"); } }
	public static Color PissYellow { get { return ColorTranslator.FromHTML("#ddd618"); } }
	public static Color BrightCyan { get { return ColorTranslator.FromHTML("#41fdfe"); } }
	public static Color DarkCoral { get { return ColorTranslator.FromHTML("#cf524e"); } }
	public static Color AlgaeGreen { get { return ColorTranslator.FromHTML("#21c36f"); } }
	public static Color DarkishRed { get { return ColorTranslator.FromHTML("#a90308"); } }
	public static Color ReddyBrown { get { return ColorTranslator.FromHTML("#6e1005"); } }
	public static Color BlushPink { get { return ColorTranslator.FromHTML("#fe828c"); } }
	public static Color CamouflageGreen { get { return ColorTranslator.FromHTML("#4b6113"); } }
	public static Color LawnGreen { get { return ColorTranslator.FromHTML("#4da409"); } }
	public static Color Putty { get { return ColorTranslator.FromHTML("#beae8a"); } }
	public static Color VibrantBlue { get { return ColorTranslator.FromHTML("#0339f8"); } }
	public static Color DarkSand { get { return ColorTranslator.FromHTML("#a88f59"); } }
	public static Color Purple_Blue { get { return ColorTranslator.FromHTML("#5d21d0"); } }
	public static Color Saffron { get { return ColorTranslator.FromHTML("#feb209"); } }
	public static Color Twilight { get { return ColorTranslator.FromHTML("#4e518b"); } }
	public static Color WarmBrown { get { return ColorTranslator.FromHTML("#964e02"); } }
	public static Color Bluegrey { get { return ColorTranslator.FromHTML("#85a3b2"); } }
	public static Color BubbleGumPink { get { return ColorTranslator.FromHTML("#ff69af"); } }
	public static Color DuckEggBlue { get { return ColorTranslator.FromHTML("#c3fbf4"); } }
	public static Color GreenishCyan { get { return ColorTranslator.FromHTML("#2afeb7"); } }
	public static Color Petrol { get { return ColorTranslator.FromHTML("#005f6a"); } }
	public static Color Royal { get { return ColorTranslator.FromHTML("#0c1793"); } }
	public static Color Butter { get { return ColorTranslator.FromHTML("#ffff81"); } }
	public static Color DustyOrange { get { return ColorTranslator.FromHTML("#f0833a"); } }
	public static Color OffYellow { get { return ColorTranslator.FromHTML("#f1f33f"); } }
	public static Color PaleOliveGreen { get { return ColorTranslator.FromHTML("#b1d27b"); } }
	public static Color Orangish { get { return ColorTranslator.FromHTML("#fc824a"); } }
	public static Color Leaf { get { return ColorTranslator.FromHTML("#71aa34"); } }
	public static Color LightBlueGrey { get { return ColorTranslator.FromHTML("#b7c9e2"); } }
	public static Color DriedBlood { get { return ColorTranslator.FromHTML("#4b0101"); } }
	public static Color LightishPurple { get { return ColorTranslator.FromHTML("#a552e6"); } }
	public static Color RustyRed { get { return ColorTranslator.FromHTML("#af2f0d"); } }
	public static Color LavenderBlue { get { return ColorTranslator.FromHTML("#8b88f8"); } }
	public static Color LightGrassGreen { get { return ColorTranslator.FromHTML("#9af764"); } }
	public static Color LightMintGreen { get { return ColorTranslator.FromHTML("#a6fbb2"); } }
	public static Color Sunflower { get { return ColorTranslator.FromHTML("#ffc512"); } }
	public static Color Velvet { get { return ColorTranslator.FromHTML("#750851"); } }
	public static Color BrickOrange { get { return ColorTranslator.FromHTML("#c14a09"); } }
	public static Color LightishRed { get { return ColorTranslator.FromHTML("#fe2f4a"); } }
	public static Color PureBlue { get { return ColorTranslator.FromHTML("#0203e2"); } }
	public static Color TwilightBlue { get { return ColorTranslator.FromHTML("#0a437a"); } }
	public static Color VioletRed { get { return ColorTranslator.FromHTML("#a50055"); } }
	public static Color YellowyBrown { get { return ColorTranslator.FromHTML("#ae8b0c"); } }
	public static Color Carnation { get { return ColorTranslator.FromHTML("#fd798f"); } }
	public static Color MuddyYellow { get { return ColorTranslator.FromHTML("#bfac05"); } }
	public static Color DarkSeafoamGreen { get { return ColorTranslator.FromHTML("#3eaf76"); } }
	public static Color DeepRose { get { return ColorTranslator.FromHTML("#c74767"); } }
	public static Color DustyRed { get { return ColorTranslator.FromHTML("#b9484e"); } }
	public static Color Grey_Blue { get { return ColorTranslator.FromHTML("#647d8e"); } }
	public static Color LemonLime { get { return ColorTranslator.FromHTML("#bffe28"); } }
	public static Color Purple_Pink { get { return ColorTranslator.FromHTML("#d725de"); } }
	public static Color BrownYellow { get { return ColorTranslator.FromHTML("#b29705"); } }
	public static Color PurpleBrown { get { return ColorTranslator.FromHTML("#673a3f"); } }
	public static Color Wisteria { get { return ColorTranslator.FromHTML("#a87dc2"); } }
	public static Color BananaYellow { get { return ColorTranslator.FromHTML("#fafe4b"); } }
	public static Color LipstickRed { get { return ColorTranslator.FromHTML("#c0022f"); } }
	public static Color WaterBlue { get { return ColorTranslator.FromHTML("#0e87cc"); } }
	public static Color BrownGrey { get { return ColorTranslator.FromHTML("#8d8468"); } }
	public static Color VibrantPurple { get { return ColorTranslator.FromHTML("#ad03de"); } }
	public static Color BabyGreen { get { return ColorTranslator.FromHTML("#8cff9e"); } }
	public static Color BarfGreen { get { return ColorTranslator.FromHTML("#94ac02"); } }
	public static Color EggshellBlue { get { return ColorTranslator.FromHTML("#c4fff7"); } }
	public static Color SandyYellow { get { return ColorTranslator.FromHTML("#fdee73"); } }
	public static Color CoolGreen { get { return ColorTranslator.FromHTML("#33b864"); } }
	public static Color Pale { get { return ColorTranslator.FromHTML("#fff9d0"); } }
	public static Color Blue_Grey { get { return ColorTranslator.FromHTML("#758da3"); } }
	public static Color HotMagenta { get { return ColorTranslator.FromHTML("#f504c9"); } }
	public static Color Greyblue { get { return ColorTranslator.FromHTML("#77a1b5"); } }
	public static Color Purpley { get { return ColorTranslator.FromHTML("#8756e4"); } }
	public static Color BabyShitGreen { get { return ColorTranslator.FromHTML("#889717"); } }
	public static Color BrownishPink { get { return ColorTranslator.FromHTML("#c27e79"); } }
	public static Color DarkAquamarine { get { return ColorTranslator.FromHTML("#017371"); } }
	public static Color Diarrhea { get { return ColorTranslator.FromHTML("#9f8303"); } }
	public static Color LightMustard { get { return ColorTranslator.FromHTML("#f7d560"); } }
	public static Color PaleSkyBlue { get { return ColorTranslator.FromHTML("#bdf6fe"); } }
	public static Color TurtleGreen { get { return ColorTranslator.FromHTML("#75b84f"); } }
	public static Color BrightOlive { get { return ColorTranslator.FromHTML("#9cbb04"); } }
	public static Color DarkGreyBlue { get { return ColorTranslator.FromHTML("#29465b"); } }
	public static Color GreenyBrown { get { return ColorTranslator.FromHTML("#696006"); } }
	public static Color LemonGreen { get { return ColorTranslator.FromHTML("#adf802"); } }
	public static Color LightPeriwinkle { get { return ColorTranslator.FromHTML("#c1c6fc"); } }
	public static Color SeaweedGreen { get { return ColorTranslator.FromHTML("#35ad6b"); } }
	public static Color SunshineYellow { get { return ColorTranslator.FromHTML("#fffd37"); } }
	public static Color UglyPurple { get { return ColorTranslator.FromHTML("#a442a0"); } }
	public static Color MediumPink { get { return ColorTranslator.FromHTML("#f36196"); } }
	public static Color PukeBrown { get { return ColorTranslator.FromHTML("#947706"); } }
	public static Color VeryLightPink { get { return ColorTranslator.FromHTML("#fff4f2"); } }
	public static Color Viridian { get { return ColorTranslator.FromHTML("#1e9167"); } }
	public static Color Bile { get { return ColorTranslator.FromHTML("#b5c306"); } }
	public static Color FadedYellow { get { return ColorTranslator.FromHTML("#feff7f"); } }
	public static Color VeryPaleGreen { get { return ColorTranslator.FromHTML("#cffdbc"); } }
	public static Color VibrantGreen { get { return ColorTranslator.FromHTML("#0add08"); } }
	public static Color BrightLime { get { return ColorTranslator.FromHTML("#87fd05"); } }
	public static Color Spearmint { get { return ColorTranslator.FromHTML("#1ef876"); } }
	public static Color LightAquamarine { get { return ColorTranslator.FromHTML("#7bfdc7"); } }
	public static Color LightSage { get { return ColorTranslator.FromHTML("#bcecac"); } }
	public static Color Yellowgreen { get { return ColorTranslator.FromHTML("#bbf90f"); } }
	public static Color BabyPoo { get { return ColorTranslator.FromHTML("#ab9004"); } }
	public static Color DarkSeafoam { get { return ColorTranslator.FromHTML("#1fb57a"); } }
	public static Color DeepTeal { get { return ColorTranslator.FromHTML("#00555a"); } }
	public static Color Heather { get { return ColorTranslator.FromHTML("#a484ac"); } }
	public static Color RustOrange { get { return ColorTranslator.FromHTML("#c45508"); } }
	public static Color DirtyBlue { get { return ColorTranslator.FromHTML("#3f829d"); } }
	public static Color FernGreen { get { return ColorTranslator.FromHTML("#548d44"); } }
	public static Color BrightLilac { get { return ColorTranslator.FromHTML("#c95efb"); } }
	public static Color WeirdGreen { get { return ColorTranslator.FromHTML("#3ae57f"); } }
	public static Color PeacockBlue { get { return ColorTranslator.FromHTML("#016795"); } }
	public static Color AvocadoGreen { get { return ColorTranslator.FromHTML("#87a922"); } }
	public static Color FadedOrange { get { return ColorTranslator.FromHTML("#f0944d"); } }
	public static Color GrapePurple { get { return ColorTranslator.FromHTML("#5d1451"); } }
	public static Color HotGreen { get { return ColorTranslator.FromHTML("#25ff29"); } }
	public static Color LimeYellow { get { return ColorTranslator.FromHTML("#d0fe1d"); } }
	public static Color Mango { get { return ColorTranslator.FromHTML("#ffa62b"); } }
	public static Color Shamrock { get { return ColorTranslator.FromHTML("#01b44c"); } }
	public static Color Bubblegum { get { return ColorTranslator.FromHTML("#ff6cb5"); } }
	public static Color PurplishBrown { get { return ColorTranslator.FromHTML("#6b4247"); } }
	public static Color VomitYellow { get { return ColorTranslator.FromHTML("#c7c10c"); } }
	public static Color PaleCyan { get { return ColorTranslator.FromHTML("#b7fffa"); } }
	public static Color KeyLime { get { return ColorTranslator.FromHTML("#aeff6e"); } }
	public static Color TomatoRed { get { return ColorTranslator.FromHTML("#ec2d01"); } }
	public static Color Lightgreen { get { return ColorTranslator.FromHTML("#76ff7b"); } }
	public static Color Merlot { get { return ColorTranslator.FromHTML("#730039"); } }
	public static Color NightBlue { get { return ColorTranslator.FromHTML("#040348"); } }
	public static Color PurpleishPink { get { return ColorTranslator.FromHTML("#df4ec8"); } }
	public static Color Apple { get { return ColorTranslator.FromHTML("#6ecb3c"); } }
	public static Color BabyPoopGreen { get { return ColorTranslator.FromHTML("#8f9805"); } }
	public static Color GreenApple { get { return ColorTranslator.FromHTML("#5edc1f"); } }
	public static Color Heliotrope { get { return ColorTranslator.FromHTML("#d94ff5"); } }
	public static Color Yellow_Green { get { return ColorTranslator.FromHTML("#c8fd3d"); } }
	public static Color AlmostBlack { get { return ColorTranslator.FromHTML("#070d0d"); } }
	public static Color CoolBlue { get { return ColorTranslator.FromHTML("#4984b8"); } }
	public static Color LeafyGreen { get { return ColorTranslator.FromHTML("#51b73b"); } }
	public static Color MustardBrown { get { return ColorTranslator.FromHTML("#ac7e04"); } }
	public static Color Dusk { get { return ColorTranslator.FromHTML("#4e5481"); } }
	public static Color DullBrown { get { return ColorTranslator.FromHTML("#876e4b"); } }
	public static Color FrogGreen { get { return ColorTranslator.FromHTML("#58bc08"); } }
	public static Color VividGreen { get { return ColorTranslator.FromHTML("#2fef10"); } }
	public static Color BrightLightGreen { get { return ColorTranslator.FromHTML("#2dfe54"); } }
	public static Color FluroGreen { get { return ColorTranslator.FromHTML("#0aff02"); } }
	public static Color Kiwi { get { return ColorTranslator.FromHTML("#9cef43"); } }
	public static Color Seaweed { get { return ColorTranslator.FromHTML("#18d17b"); } }
	public static Color NavyGreen { get { return ColorTranslator.FromHTML("#35530a"); } }
	public static Color UltramarineBlue { get { return ColorTranslator.FromHTML("#1805db"); } }
	public static Color Iris { get { return ColorTranslator.FromHTML("#6258c4"); } }
	public static Color PastelOrange { get { return ColorTranslator.FromHTML("#ff964f"); } }
	public static Color YellowishOrange { get { return ColorTranslator.FromHTML("#ffab0f"); } }
	public static Color Perrywinkle { get { return ColorTranslator.FromHTML("#8f8ce7"); } }
	public static Color Tealish { get { return ColorTranslator.FromHTML("#24bca8"); } }
	public static Color DarkPlum { get { return ColorTranslator.FromHTML("#3f012c"); } }
	public static Color Pear { get { return ColorTranslator.FromHTML("#cbf85f"); } }
	public static Color PinkishOrange { get { return ColorTranslator.FromHTML("#ff724c"); } }
	public static Color MidnightPurple { get { return ColorTranslator.FromHTML("#280137"); } }
	public static Color LightUrple { get { return ColorTranslator.FromHTML("#b36ff6"); } }
	public static Color DarkMint { get { return ColorTranslator.FromHTML("#48c072"); } }
	public static Color GreenishTan { get { return ColorTranslator.FromHTML("#bccb7a"); } }
	public static Color LightBurgundy { get { return ColorTranslator.FromHTML("#a8415b"); } }
	public static Color TurquoiseBlue { get { return ColorTranslator.FromHTML("#06b1c4"); } }
	public static Color UglyPink { get { return ColorTranslator.FromHTML("#cd7584"); } }
	public static Color Sandy { get { return ColorTranslator.FromHTML("#f1da7a"); } }
	public static Color ElectricPink { get { return ColorTranslator.FromHTML("#ff0490"); } }
	public static Color MutedPurple { get { return ColorTranslator.FromHTML("#805b87"); } }
	public static Color MidGreen { get { return ColorTranslator.FromHTML("#50a747"); } }
	public static Color Greyish { get { return ColorTranslator.FromHTML("#a8a495"); } }
	public static Color NeonYellow { get { return ColorTranslator.FromHTML("#cfff04"); } }
	public static Color Banana { get { return ColorTranslator.FromHTML("#ffff7e"); } }
	public static Color CarnationPink { get { return ColorTranslator.FromHTML("#ff7fa7"); } }
	public static Color Tomato { get { return ColorTranslator.FromHTML("#ef4026"); } }
	public static Color Sea { get { return ColorTranslator.FromHTML("#3c9992"); } }
	public static Color MuddyBrown { get { return ColorTranslator.FromHTML("#886806"); } }
	public static Color TurquoiseGreen { get { return ColorTranslator.FromHTML("#04f489"); } }
	public static Color Buff { get { return ColorTranslator.FromHTML("#fef69e"); } }
	public static Color Fawn { get { return ColorTranslator.FromHTML("#cfaf7b"); } }
	public static Color MutedBlue { get { return ColorTranslator.FromHTML("#3b719f"); } }
	public static Color PaleRose { get { return ColorTranslator.FromHTML("#fdc1c5"); } }
	public static Color DarkMintGreen { get { return ColorTranslator.FromHTML("#20c073"); } }
	public static Color Amethyst { get { return ColorTranslator.FromHTML("#9b5fc0"); } }
	public static Color Blue_Green { get { return ColorTranslator.FromHTML("#0f9b8e"); } }
	public static Color Chestnut { get { return ColorTranslator.FromHTML("#742802"); } }
	public static Color SickGreen { get { return ColorTranslator.FromHTML("#9db92c"); } }
	public static Color Pea { get { return ColorTranslator.FromHTML("#a4bf20"); } }
	public static Color RustyOrange { get { return ColorTranslator.FromHTML("#cd5909"); } }
	public static Color Stone { get { return ColorTranslator.FromHTML("#ada587"); } }
	public static Color RoseRed { get { return ColorTranslator.FromHTML("#be013c"); } }
	public static Color PaleAqua { get { return ColorTranslator.FromHTML("#b8ffeb"); } }
	public static Color DeepOrange { get { return ColorTranslator.FromHTML("#dc4d01"); } }
	public static Color Earth { get { return ColorTranslator.FromHTML("#a2653e"); } }
	public static Color MossyGreen { get { return ColorTranslator.FromHTML("#638b27"); } }
	public static Color GrassyGreen { get { return ColorTranslator.FromHTML("#419c03"); } }
	public static Color PaleLimeGreen { get { return ColorTranslator.FromHTML("#b1ff65"); } }
	public static Color LightGreyBlue { get { return ColorTranslator.FromHTML("#9dbcd4"); } }
	public static Color PaleGrey { get { return ColorTranslator.FromHTML("#fdfdfe"); } }
	public static Color Asparagus { get { return ColorTranslator.FromHTML("#77ab56"); } }
	public static Color Blueberry { get { return ColorTranslator.FromHTML("#464196"); } }
	public static Color PurpleRed { get { return ColorTranslator.FromHTML("#990147"); } }
	public static Color PaleLime { get { return ColorTranslator.FromHTML("#befd73"); } }
	public static Color GreenishTeal { get { return ColorTranslator.FromHTML("#32bf84"); } }
	public static Color Caramel { get { return ColorTranslator.FromHTML("#af6f09"); } }
	public static Color DeepMagenta { get { return ColorTranslator.FromHTML("#a0025c"); } }
	public static Color LightPeach { get { return ColorTranslator.FromHTML("#ffd8b1"); } }
	public static Color MilkChocolate { get { return ColorTranslator.FromHTML("#7f4e1e"); } }
	public static Color Ocher { get { return ColorTranslator.FromHTML("#bf9b0c"); } }
	public static Color OffGreen { get { return ColorTranslator.FromHTML("#6ba353"); } }
	public static Color PurplyPink { get { return ColorTranslator.FromHTML("#f075e6"); } }
	public static Color Lightblue { get { return ColorTranslator.FromHTML("#7bc8f6"); } }
	public static Color DuskyBlue { get { return ColorTranslator.FromHTML("#475f94"); } }
	public static Color Golden { get { return ColorTranslator.FromHTML("#f5bf03"); } }
	public static Color LightBeige { get { return ColorTranslator.FromHTML("#fffeb6"); } }
	public static Color ButterYellow { get { return ColorTranslator.FromHTML("#fffd74"); } }
	public static Color DuskyPurple { get { return ColorTranslator.FromHTML("#895b7b"); } }
	public static Color FrenchBlue { get { return ColorTranslator.FromHTML("#436bad"); } }
	public static Color UglyYellow { get { return ColorTranslator.FromHTML("#d0c101"); } }
	public static Color GreenyYellow { get { return ColorTranslator.FromHTML("#c6f808"); } }
	public static Color OrangishRed { get { return ColorTranslator.FromHTML("#f43605"); } }
	public static Color ShamrockGreen { get { return ColorTranslator.FromHTML("#02c14d"); } }
	public static Color OrangishBrown { get { return ColorTranslator.FromHTML("#b25f03"); } }
	public static Color TreeGreen { get { return ColorTranslator.FromHTML("#2a7e19"); } }
	public static Color DeepViolet { get { return ColorTranslator.FromHTML("#490648"); } }
	public static Color Gunmetal { get { return ColorTranslator.FromHTML("#536267"); } }
	public static Color Blue_Purple { get { return ColorTranslator.FromHTML("#5a06ef"); } }
	public static Color Cherry { get { return ColorTranslator.FromHTML("#cf0234"); } }
	public static Color SandyBrown { get { return ColorTranslator.FromHTML("#c4a661"); } }
	public static Color WarmGrey { get { return ColorTranslator.FromHTML("#978a84"); } }
	public static Color DarkIndigo { get { return ColorTranslator.FromHTML("#1f0954"); } }
	public static Color Midnight { get { return ColorTranslator.FromHTML("#03012d"); } }
	public static Color BlueyGreen { get { return ColorTranslator.FromHTML("#2bb179"); } }
	public static Color GreyPink { get { return ColorTranslator.FromHTML("#c3909b"); } }
	public static Color SoftPurple { get { return ColorTranslator.FromHTML("#a66fb5"); } }
	public static Color Blood { get { return ColorTranslator.FromHTML("#770001"); } }
	public static Color BrownRed { get { return ColorTranslator.FromHTML("#922b05"); } }
	public static Color MediumGrey { get { return ColorTranslator.FromHTML("#7d7f7c"); } }
	public static Color Berry { get { return ColorTranslator.FromHTML("#990f4b"); } }
	public static Color Poo { get { return ColorTranslator.FromHTML("#8f7303"); } }
	public static Color PurpleyPink { get { return ColorTranslator.FromHTML("#c83cb9"); } }
	public static Color LightSalmon { get { return ColorTranslator.FromHTML("#fea993"); } }
	public static Color Snot { get { return ColorTranslator.FromHTML("#acbb0d"); } }
	public static Color EasterPurple { get { return ColorTranslator.FromHTML("#c071fe"); } }
	public static Color LightYellowGreen { get { return ColorTranslator.FromHTML("#ccfd7f"); } }
	public static Color DarkNavyBlue { get { return ColorTranslator.FromHTML("#00022e"); } }
	public static Color Drab { get { return ColorTranslator.FromHTML("#828344"); } }
	public static Color LightRose { get { return ColorTranslator.FromHTML("#ffc5cb"); } }
	public static Color Rouge { get { return ColorTranslator.FromHTML("#ab1239"); } }
	public static Color PurplishRed { get { return ColorTranslator.FromHTML("#b0054b"); } }
	public static Color SlimeGreen { get { return ColorTranslator.FromHTML("#99cc04"); } }
	public static Color BabyPoop { get { return ColorTranslator.FromHTML("#937c00"); } }
	public static Color IrishGreen { get { return ColorTranslator.FromHTML("#019529"); } }
	public static Color Pink_Purple { get { return ColorTranslator.FromHTML("#ef1de7"); } }
	public static Color DarkNavy { get { return ColorTranslator.FromHTML("#000435"); } }
	public static Color GreenyBlue { get { return ColorTranslator.FromHTML("#42b395"); } }
	public static Color LightPlum { get { return ColorTranslator.FromHTML("#9d5783"); } }
	public static Color PinkishGrey { get { return ColorTranslator.FromHTML("#c8aca9"); } }
	public static Color DirtyOrange { get { return ColorTranslator.FromHTML("#c87606"); } }
	public static Color RustRed { get { return ColorTranslator.FromHTML("#aa2704"); } }
	public static Color PaleLilac { get { return ColorTranslator.FromHTML("#e4cbff"); } }
	public static Color OrangeyRed { get { return ColorTranslator.FromHTML("#fa4224"); } }
	public static Color PrimaryBlue { get { return ColorTranslator.FromHTML("#0804f9"); } }
	public static Color KermitGreen { get { return ColorTranslator.FromHTML("#5cb200"); } }
	public static Color BrownishPurple { get { return ColorTranslator.FromHTML("#76424e"); } }
	public static Color MurkyGreen { get { return ColorTranslator.FromHTML("#6c7a0e"); } }
	public static Color Wheat { get { return ColorTranslator.FromHTML("#fbdd7e"); } }
	public static Color VeryDarkPurple { get { return ColorTranslator.FromHTML("#2a0134"); } }
	public static Color BottleGreen { get { return ColorTranslator.FromHTML("#044a05"); } }
	public static Color Watermelon { get { return ColorTranslator.FromHTML("#fd4659"); } }
	public static Color DeepSkyBlue { get { return ColorTranslator.FromHTML("#0d75f8"); } }
	public static Color FireEngineRed { get { return ColorTranslator.FromHTML("#fe0002"); } }
	public static Color YellowOchre { get { return ColorTranslator.FromHTML("#cb9d06"); } }
	public static Color PumpkinOrange { get { return ColorTranslator.FromHTML("#fb7d07"); } }
	public static Color PaleOlive { get { return ColorTranslator.FromHTML("#b9cc81"); } }
	public static Color LightLilac { get { return ColorTranslator.FromHTML("#edc8ff"); } }
	public static Color LightishGreen { get { return ColorTranslator.FromHTML("#61e160"); } }
	public static Color CarolinaBlue { get { return ColorTranslator.FromHTML("#8ab8fe"); } }
	public static Color Mulberry { get { return ColorTranslator.FromHTML("#920a4e"); } }
	public static Color ShockingPink { get { return ColorTranslator.FromHTML("#fe02a2"); } }
	public static Color Auburn { get { return ColorTranslator.FromHTML("#9a3001"); } }
	public static Color BrightLimeGreen { get { return ColorTranslator.FromHTML("#65fe08"); } }
	public static Color Celadon { get { return ColorTranslator.FromHTML("#befdb7"); } }
	public static Color PinkishBrown { get { return ColorTranslator.FromHTML("#b17261"); } }
	public static Color PooBrown { get { return ColorTranslator.FromHTML("#885f01"); } }
	public static Color BrightSkyBlue { get { return ColorTranslator.FromHTML("#02ccfe"); } }
	public static Color Celery { get { return ColorTranslator.FromHTML("#c1fd95"); } }
	public static Color DirtBrown { get { return ColorTranslator.FromHTML("#836539"); } }
	public static Color Strawberry { get { return ColorTranslator.FromHTML("#fb2943"); } }
	public static Color DarkLime { get { return ColorTranslator.FromHTML("#84b701"); } }
	public static Color Copper { get { return ColorTranslator.FromHTML("#b66325"); } }
	public static Color MediumBrown { get { return ColorTranslator.FromHTML("#7f5112"); } }
	public static Color MutedGreen { get { return ColorTranslator.FromHTML("#5fa052"); } }
	public static Color RobinSEgg { get { return ColorTranslator.FromHTML("#6dedfd"); } }
	public static Color BrightAqua { get { return ColorTranslator.FromHTML("#0bf9ea"); } }
	public static Color BrightLavender { get { return ColorTranslator.FromHTML("#c760ff"); } }
	public static Color Ivory { get { return ColorTranslator.FromHTML("#ffffcb"); } }
	public static Color VeryLightPurple { get { return ColorTranslator.FromHTML("#f6cefc"); } }
	public static Color LightNavy { get { return ColorTranslator.FromHTML("#155084"); } }
	public static Color PinkRed { get { return ColorTranslator.FromHTML("#f5054f"); } }
	public static Color OliveBrown { get { return ColorTranslator.FromHTML("#645403"); } }
	public static Color PoopBrown { get { return ColorTranslator.FromHTML("#7a5901"); } }
	public static Color MustardGreen { get { return ColorTranslator.FromHTML("#a8b504"); } }
	public static Color OceanGreen { get { return ColorTranslator.FromHTML("#3d9973"); } }
	public static Color VeryDarkBlue { get { return ColorTranslator.FromHTML("#000133"); } }
	public static Color DustyGreen { get { return ColorTranslator.FromHTML("#76a973"); } }
	public static Color LightNavyBlue { get { return ColorTranslator.FromHTML("#2e5a88"); } }
	public static Color MintyGreen { get { return ColorTranslator.FromHTML("#0bf77d"); } }
	public static Color Adobe { get { return ColorTranslator.FromHTML("#bd6c48"); } }
	public static Color Barney { get { return ColorTranslator.FromHTML("#ac1db8"); } }
	public static Color JadeGreen { get { return ColorTranslator.FromHTML("#2baf6a"); } }
	public static Color BrightLightBlue { get { return ColorTranslator.FromHTML("#26f7fd"); } }
	public static Color LightLime { get { return ColorTranslator.FromHTML("#aefd6c"); } }
	public static Color DarkKhaki { get { return ColorTranslator.FromHTML("#9b8f55"); } }
	public static Color OrangeYellow { get { return ColorTranslator.FromHTML("#ffad01"); } }
	public static Color Ocre { get { return ColorTranslator.FromHTML("#c69c04"); } }
	public static Color Maize { get { return ColorTranslator.FromHTML("#f4d054"); } }
	public static Color FadedPink { get { return ColorTranslator.FromHTML("#de9dac"); } }
	public static Color BritishRacingGreen { get { return ColorTranslator.FromHTML("#05480d"); } }
	public static Color Sandstone { get { return ColorTranslator.FromHTML("#c9ae74"); } }
	public static Color MudBrown { get { return ColorTranslator.FromHTML("#60460f"); } }
	public static Color LightSeaGreen { get { return ColorTranslator.FromHTML("#98f6b0"); } }
	public static Color RobinEggBlue { get { return ColorTranslator.FromHTML("#8af1fe"); } }
	public static Color AquaMarine { get { return ColorTranslator.FromHTML("#2ee8bb"); } }
	public static Color DarkSeaGreen { get { return ColorTranslator.FromHTML("#11875d"); } }
	public static Color SoftPink { get { return ColorTranslator.FromHTML("#fdb0c0"); } }
	public static Color OrangeyBrown { get { return ColorTranslator.FromHTML("#b16002"); } }
	public static Color CherryRed { get { return ColorTranslator.FromHTML("#f7022a"); } }
	public static Color BurntYellow { get { return ColorTranslator.FromHTML("#d5ab09"); } }
	public static Color BrownishGrey { get { return ColorTranslator.FromHTML("#86775f"); } }
	public static Color Camel { get { return ColorTranslator.FromHTML("#c69f59"); } }
	public static Color PurplishGrey { get { return ColorTranslator.FromHTML("#7a687f"); } }
	public static Color Marine { get { return ColorTranslator.FromHTML("#042e60"); } }
	public static Color GreyishPink { get { return ColorTranslator.FromHTML("#c88d94"); } }
	public static Color PaleTurquoise { get { return ColorTranslator.FromHTML("#a5fbd5"); } }
	public static Color PastelYellow { get { return ColorTranslator.FromHTML("#fffe71"); } }
	public static Color BlueyPurple { get { return ColorTranslator.FromHTML("#6241c7"); } }
	public static Color CanaryYellow { get { return ColorTranslator.FromHTML("#fffe40"); } }
	public static Color FadedRed { get { return ColorTranslator.FromHTML("#d3494e"); } }
	public static Color Sepia { get { return ColorTranslator.FromHTML("#985e2b"); } }
	public static Color Coffee { get { return ColorTranslator.FromHTML("#a6814c"); } }
	public static Color BrightMagenta { get { return ColorTranslator.FromHTML("#ff08e8"); } }
	public static Color Mocha { get { return ColorTranslator.FromHTML("#9d7651"); } }
	public static Color Ecru { get { return ColorTranslator.FromHTML("#feffca"); } }
	public static Color Purpleish { get { return ColorTranslator.FromHTML("#98568d"); } }
	public static Color Cranberry { get { return ColorTranslator.FromHTML("#9e003a"); } }
	public static Color DarkishGreen { get { return ColorTranslator.FromHTML("#287c37"); } }
	public static Color BrownOrange { get { return ColorTranslator.FromHTML("#b96902"); } }
	public static Color DuskyRose { get { return ColorTranslator.FromHTML("#ba6873"); } }
	public static Color Melon { get { return ColorTranslator.FromHTML("#ff7855"); } }
	public static Color SicklyGreen { get { return ColorTranslator.FromHTML("#94b21c"); } }
	public static Color Silver { get { return ColorTranslator.FromHTML("#c5c9c7"); } }
	public static Color PurplyBlue { get { return ColorTranslator.FromHTML("#661aee"); } }
	public static Color PurpleishBlue { get { return ColorTranslator.FromHTML("#6140ef"); } }
	public static Color HospitalGreen { get { return ColorTranslator.FromHTML("#9be5aa"); } }
	public static Color ShitBrown { get { return ColorTranslator.FromHTML("#7b5804"); } }
	public static Color MidBlue { get { return ColorTranslator.FromHTML("#276ab3"); } }
	public static Color Amber { get { return ColorTranslator.FromHTML("#feb308"); } }
	public static Color EasterGreen { get { return ColorTranslator.FromHTML("#8cfd7e"); } }
	public static Color SoftBlue { get { return ColorTranslator.FromHTML("#6488ea"); } }
	public static Color CeruleanBlue { get { return ColorTranslator.FromHTML("#056eee"); } }
	public static Color GoldenBrown { get { return ColorTranslator.FromHTML("#b27a01"); } }
	public static Color BrightTurquoise { get { return ColorTranslator.FromHTML("#0ffef9"); } }
	public static Color RedPink { get { return ColorTranslator.FromHTML("#fa2a55"); } }
	public static Color RedPurple { get { return ColorTranslator.FromHTML("#820747"); } }
	public static Color GreyishBrown { get { return ColorTranslator.FromHTML("#7a6a4f"); } }
	public static Color Vermillion { get { return ColorTranslator.FromHTML("#f4320c"); } }
	public static Color Russet { get { return ColorTranslator.FromHTML("#a13905"); } }
	public static Color SteelGrey { get { return ColorTranslator.FromHTML("#6f828a"); } }
	public static Color LighterPurple { get { return ColorTranslator.FromHTML("#a55af4"); } }
	public static Color BrightViolet { get { return ColorTranslator.FromHTML("#ad0afd"); } }
	public static Color PrussianBlue { get { return ColorTranslator.FromHTML("#004577"); } }
	public static Color SlateGreen { get { return ColorTranslator.FromHTML("#658d6d"); } }
	public static Color DirtyPink { get { return ColorTranslator.FromHTML("#ca7b80"); } }
	public static Color DarkBlueGreen { get { return ColorTranslator.FromHTML("#005249"); } }
	public static Color Pine { get { return ColorTranslator.FromHTML("#2b5d34"); } }
	public static Color YellowyGreen { get { return ColorTranslator.FromHTML("#bff128"); } }
	public static Color DarkGold { get { return ColorTranslator.FromHTML("#b59410"); } }
	public static Color Bluish { get { return ColorTranslator.FromHTML("#2976bb"); } }
	public static Color DarkishBlue { get { return ColorTranslator.FromHTML("#014182"); } }
	public static Color DullRed { get { return ColorTranslator.FromHTML("#bb3f3f"); } }
	public static Color PinkyRed { get { return ColorTranslator.FromHTML("#fc2647"); } }
	public static Color Bronze { get { return ColorTranslator.FromHTML("#a87900"); } }
	public static Color PaleTeal { get { return ColorTranslator.FromHTML("#82cbb2"); } }
	public static Color MilitaryGreen { get { return ColorTranslator.FromHTML("#667c3e"); } }
	public static Color BarbiePink { get { return ColorTranslator.FromHTML("#fe46a5"); } }
	public static Color BubblegumPink { get { return ColorTranslator.FromHTML("#fe83cc"); } }
	public static Color PeaSoupGreen { get { return ColorTranslator.FromHTML("#94a617"); } }
	public static Color DarkMustard { get { return ColorTranslator.FromHTML("#a88905"); } }
	public static Color Shit { get { return ColorTranslator.FromHTML("#7f5f00"); } }
	public static Color MediumPurple { get { return ColorTranslator.FromHTML("#9e43a2"); } }
	public static Color VeryDarkGreen { get { return ColorTranslator.FromHTML("#062e03"); } }
	public static Color Dirt { get { return ColorTranslator.FromHTML("#8a6e45"); } }
	public static Color DuskyPink { get { return ColorTranslator.FromHTML("#cc7a8b"); } }
	public static Color RedViolet { get { return ColorTranslator.FromHTML("#9e0168"); } }
	public static Color LemonYellow { get { return ColorTranslator.FromHTML("#fdff38"); } }
	public static Color Pistachio { get { return ColorTranslator.FromHTML("#c0fa8b"); } }
	public static Color DullYellow { get { return ColorTranslator.FromHTML("#eedc5b"); } }
	public static Color DarkLimeGreen { get { return ColorTranslator.FromHTML("#7ebd01"); } }
	public static Color DenimBlue { get { return ColorTranslator.FromHTML("#3b5b92"); } }
	public static Color TealBlue { get { return ColorTranslator.FromHTML("#01889f"); } }
	public static Color LightishBlue { get { return ColorTranslator.FromHTML("#3d7afd"); } }
	public static Color PurpleyBlue { get { return ColorTranslator.FromHTML("#5f34e7"); } }
	public static Color LightIndigo { get { return ColorTranslator.FromHTML("#6d5acf"); } }
	public static Color SwampGreen { get { return ColorTranslator.FromHTML("#748500"); } }
	public static Color BrownGreen { get { return ColorTranslator.FromHTML("#706c11"); } }
	public static Color DarkMaroon { get { return ColorTranslator.FromHTML("#3c0008"); } }
	public static Color HotPurple { get { return ColorTranslator.FromHTML("#cb00f5"); } }
	public static Color DarkForestGreen { get { return ColorTranslator.FromHTML("#002d04"); } }
	public static Color FadedBlue { get { return ColorTranslator.FromHTML("#658cbb"); } }
	public static Color DrabGreen { get { return ColorTranslator.FromHTML("#749551"); } }
	public static Color LightLimeGreen { get { return ColorTranslator.FromHTML("#b9ff66"); } }
	public static Color SnotGreen { get { return ColorTranslator.FromHTML("#9dc100"); } }
	public static Color Yellowish { get { return ColorTranslator.FromHTML("#faee66"); } }
	public static Color LightBlueGreen { get { return ColorTranslator.FromHTML("#7efbb3"); } }
	public static Color Bordeaux { get { return ColorTranslator.FromHTML("#7b002c"); } }
	public static Color LightMauve { get { return ColorTranslator.FromHTML("#c292a1"); } }
	public static Color Ocean { get { return ColorTranslator.FromHTML("#017b92"); } }
	public static Color Marigold { get { return ColorTranslator.FromHTML("#fcc006"); } }
	public static Color MuddyGreen { get { return ColorTranslator.FromHTML("#657432"); } }
	public static Color DullOrange { get { return ColorTranslator.FromHTML("#d8863b"); } }
	public static Color Steel { get { return ColorTranslator.FromHTML("#738595"); } }
	public static Color ElectricPurple { get { return ColorTranslator.FromHTML("#aa23ff"); } }
	public static Color FluorescentGreen { get { return ColorTranslator.FromHTML("#08ff08"); } }
	public static Color YellowishBrown { get { return ColorTranslator.FromHTML("#9b7a01"); } }
	public static Color Blush { get { return ColorTranslator.FromHTML("#f29e8e"); } }
	public static Color SoftGreen { get { return ColorTranslator.FromHTML("#6fc276"); } }
	public static Color BrightOrange { get { return ColorTranslator.FromHTML("#ff5b00"); } }
	public static Color Lemon { get { return ColorTranslator.FromHTML("#fdff52"); } }
	public static Color PurpleGrey { get { return ColorTranslator.FromHTML("#866f85"); } }
	public static Color AcidGreen { get { return ColorTranslator.FromHTML("#8ffe09"); } }
	public static Color PaleLavender { get { return ColorTranslator.FromHTML("#eecffe"); } }
	public static Color VioletBlue { get { return ColorTranslator.FromHTML("#510ac9"); } }
	public static Color LightForestGreen { get { return ColorTranslator.FromHTML("#4f9153"); } }
	public static Color BurntRed { get { return ColorTranslator.FromHTML("#9f2305"); } }
	public static Color KhakiGreen { get { return ColorTranslator.FromHTML("#728639"); } }
	public static Color Cerise { get { return ColorTranslator.FromHTML("#de0c62"); } }
	public static Color FadedPurple { get { return ColorTranslator.FromHTML("#916e99"); } }
	public static Color Apricot { get { return ColorTranslator.FromHTML("#ffb16d"); } }
	public static Color DarkOliveGreen { get { return ColorTranslator.FromHTML("#3c4d03"); } }
	public static Color GreyBrown { get { return ColorTranslator.FromHTML("#7f7053"); } }
	public static Color GreenGrey { get { return ColorTranslator.FromHTML("#77926f"); } }
	public static Color TrueBlue { get { return ColorTranslator.FromHTML("#010fcc"); } }
	public static Color PaleViolet { get { return ColorTranslator.FromHTML("#ceaefa"); } }
	public static Color PeriwinkleBlue { get { return ColorTranslator.FromHTML("#8f99fb"); } }
	public static Color LightSkyBlue { get { return ColorTranslator.FromHTML("#c6fcff"); } }
	public static Color Blurple { get { return ColorTranslator.FromHTML("#5539cc"); } }
	public static Color GreenBrown { get { return ColorTranslator.FromHTML("#544e03"); } }
	public static Color Bluegreen { get { return ColorTranslator.FromHTML("#017a79"); } }
	public static Color BrightTeal { get { return ColorTranslator.FromHTML("#01f9c6"); } }
	public static Color BrownishYellow { get { return ColorTranslator.FromHTML("#c9b003"); } }
	public static Color PeaSoup { get { return ColorTranslator.FromHTML("#929901"); } }
	public static Color Forest { get { return ColorTranslator.FromHTML("#0b5509"); } }
	public static Color BarneyPurple { get { return ColorTranslator.FromHTML("#a00498"); } }
	public static Color Ultramarine { get { return ColorTranslator.FromHTML("#2000b1"); } }
	public static Color Purplish { get { return ColorTranslator.FromHTML("#94568c"); } }
	public static Color PukeYellow { get { return ColorTranslator.FromHTML("#c2be0e"); } }
	public static Color BluishGrey { get { return ColorTranslator.FromHTML("#748b97"); } }
	public static Color DarkPeriwinkle { get { return ColorTranslator.FromHTML("#665fd1"); } }
	public static Color DarkLilac { get { return ColorTranslator.FromHTML("#9c6da5"); } }
	public static Color Reddish { get { return ColorTranslator.FromHTML("#c44240"); } }
	public static Color LightMaroon { get { return ColorTranslator.FromHTML("#a24857"); } }
	public static Color DustyPurple { get { return ColorTranslator.FromHTML("#825f87"); } }
	public static Color TerraCotta { get { return ColorTranslator.FromHTML("#c9643b"); } }
	public static Color Avocado { get { return ColorTranslator.FromHTML("#90b134"); } }
	public static Color MarineBlue { get { return ColorTranslator.FromHTML("#01386a"); } }
	public static Color TealGreen { get { return ColorTranslator.FromHTML("#25a36f"); } }
	public static Color SlateGrey { get { return ColorTranslator.FromHTML("#59656d"); } }
	public static Color LighterGreen { get { return ColorTranslator.FromHTML("#75fd63"); } }
	public static Color ElectricGreen { get { return ColorTranslator.FromHTML("#21fc0d"); } }
	public static Color DustyBlue { get { return ColorTranslator.FromHTML("#5a86ad"); } }
	public static Color GoldenYellow { get { return ColorTranslator.FromHTML("#fec615"); } }
	public static Color BrightYellow { get { return ColorTranslator.FromHTML("#fffd01"); } }
	public static Color LightLavender { get { return ColorTranslator.FromHTML("#dfc5fe"); } }
	public static Color Umber { get { return ColorTranslator.FromHTML("#b26400"); } }
	public static Color Poop { get { return ColorTranslator.FromHTML("#7f5e00"); } }
	public static Color DarkPeach { get { return ColorTranslator.FromHTML("#de7e5d"); } }
	public static Color JungleGreen { get { return ColorTranslator.FromHTML("#048243"); } }
	public static Color Eggshell { get { return ColorTranslator.FromHTML("#ffffd4"); } }
	public static Color Denim { get { return ColorTranslator.FromHTML("#3b638c"); } }
	public static Color YellowBrown { get { return ColorTranslator.FromHTML("#b79400"); } }
	public static Color DullPurple { get { return ColorTranslator.FromHTML("#84597e"); } }
	public static Color ChocolateBrown { get { return ColorTranslator.FromHTML("#411900"); } }
	public static Color WineRed { get { return ColorTranslator.FromHTML("#7b0323"); } }
	public static Color NeonBlue { get { return ColorTranslator.FromHTML("#04d9ff"); } }
	public static Color DirtyGreen { get { return ColorTranslator.FromHTML("#667e2c"); } }
	public static Color LightTan { get { return ColorTranslator.FromHTML("#fbeeac"); } }
	public static Color IceBlue { get { return ColorTranslator.FromHTML("#d7fffe"); } }
	public static Color CadetBlue { get { return ColorTranslator.FromHTML("#4e7496"); } }
	public static Color DarkMauve { get { return ColorTranslator.FromHTML("#874c62"); } }
	public static Color VeryLightBlue { get { return ColorTranslator.FromHTML("#d5ffff"); } }
	public static Color GreyPurple { get { return ColorTranslator.FromHTML("#826d8c"); } }
	public static Color PastelPink { get { return ColorTranslator.FromHTML("#ffbacd"); } }
	public static Color VeryLightGreen { get { return ColorTranslator.FromHTML("#d1ffbd"); } }
	public static Color DarkSkyBlue { get { return ColorTranslator.FromHTML("#448ee4"); } }
	public static Color Evergreen { get { return ColorTranslator.FromHTML("#05472a"); } }
	public static Color DullPink { get { return ColorTranslator.FromHTML("#d5869d"); } }
	public static Color Aubergine { get { return ColorTranslator.FromHTML("#3d0734"); } }
	public static Color Mahogany { get { return ColorTranslator.FromHTML("#4a0100"); } }
	public static Color ReddishOrange { get { return ColorTranslator.FromHTML("#f8481c"); } }
	public static Color DeepGreen { get { return ColorTranslator.FromHTML("#02590f"); } }
	public static Color VomitGreen { get { return ColorTranslator.FromHTML("#89a203"); } }
	public static Color PurplePink { get { return ColorTranslator.FromHTML("#e03fd8"); } }
	public static Color DustyPink { get { return ColorTranslator.FromHTML("#d58a94"); } }
	public static Color FadedGreen { get { return ColorTranslator.FromHTML("#7bb274"); } }
	public static Color CamoGreen { get { return ColorTranslator.FromHTML("#526525"); } }
	public static Color PinkyPurple { get { return ColorTranslator.FromHTML("#c94cbe"); } }
	public static Color PinkPurple { get { return ColorTranslator.FromHTML("#db4bda"); } }
	public static Color BrownishRed { get { return ColorTranslator.FromHTML("#9e3623"); } }
	public static Color DarkRose { get { return ColorTranslator.FromHTML("#b5485d"); } }
	public static Color Mud { get { return ColorTranslator.FromHTML("#735c12"); } }
	public static Color Brownish { get { return ColorTranslator.FromHTML("#9c6d57"); } }
	public static Color EmeraldGreen { get { return ColorTranslator.FromHTML("#028f1e"); } }
	public static Color PaleBrown { get { return ColorTranslator.FromHTML("#b1916e"); } }
	public static Color DullBlue { get { return ColorTranslator.FromHTML("#49759c"); } }
	public static Color BurntUmber { get { return ColorTranslator.FromHTML("#a0450e"); } }
	public static Color MediumGreen { get { return ColorTranslator.FromHTML("#39ad48"); } }
	public static Color Clay { get { return ColorTranslator.FromHTML("#b66a50"); } }
	public static Color LightAqua { get { return ColorTranslator.FromHTML("#8cffdb"); } }
	public static Color LightOliveGreen { get { return ColorTranslator.FromHTML("#a4be5c"); } }
	public static Color BrownishOrange { get { return ColorTranslator.FromHTML("#cb7723"); } }
	public static Color DarkAqua { get { return ColorTranslator.FromHTML("#05696b"); } }
	public static Color PurplishPink { get { return ColorTranslator.FromHTML("#ce5dae"); } }
	public static Color DarkSalmon { get { return ColorTranslator.FromHTML("#c85a53"); } }
	public static Color GreenishGrey { get { return ColorTranslator.FromHTML("#96ae8d"); } }
	public static Color Jade { get { return ColorTranslator.FromHTML("#1fa774"); } }
	public static Color UglyGreen { get { return ColorTranslator.FromHTML("#7a9703"); } }
	public static Color DarkBeige { get { return ColorTranslator.FromHTML("#ac9362"); } }
	public static Color Emerald { get { return ColorTranslator.FromHTML("#01a049"); } }
	public static Color PaleRed { get { return ColorTranslator.FromHTML("#d9544d"); } }
	public static Color LightMagenta { get { return ColorTranslator.FromHTML("#fa5ff7"); } }
	public static Color Sky { get { return ColorTranslator.FromHTML("#82cafc"); } }
	public static Color LightCyan { get { return ColorTranslator.FromHTML("#acfffc"); } }
	public static Color YellowOrange { get { return ColorTranslator.FromHTML("#fcb001"); } }
	public static Color ReddishPurple { get { return ColorTranslator.FromHTML("#910951"); } }
	public static Color ReddishPink { get { return ColorTranslator.FromHTML("#fe2c54"); } }
	public static Color Orchid { get { return ColorTranslator.FromHTML("#c875c4"); } }
	public static Color DirtyYellow { get { return ColorTranslator.FromHTML("#cdc50a"); } }
	public static Color OrangeRed { get { return ColorTranslator.FromHTML("#fd411e"); } }
	public static Color DeepRed { get { return ColorTranslator.FromHTML("#9a0200"); } }
	public static Color OrangeBrown { get { return ColorTranslator.FromHTML("#be6400"); } }
	public static Color CobaltBlue { get { return ColorTranslator.FromHTML("#030aa7"); } }
	public static Color NeonPink { get { return ColorTranslator.FromHTML("#fe019a"); } }
	public static Color RosePink { get { return ColorTranslator.FromHTML("#f7879a"); } }
	public static Color GreyishPurple { get { return ColorTranslator.FromHTML("#887191"); } }
	public static Color Raspberry { get { return ColorTranslator.FromHTML("#b00149"); } }
	public static Color AquaGreen { get { return ColorTranslator.FromHTML("#12e193"); } }
	public static Color SalmonPink { get { return ColorTranslator.FromHTML("#fe7b7c"); } }
	public static Color Tangerine { get { return ColorTranslator.FromHTML("#ff9408"); } }
	public static Color BrownishGreen { get { return ColorTranslator.FromHTML("#6a6e09"); } }
	public static Color RedBrown { get { return ColorTranslator.FromHTML("#8b2e16"); } }
	public static Color GreenishBrown { get { return ColorTranslator.FromHTML("#696112"); } }
	public static Color Pumpkin { get { return ColorTranslator.FromHTML("#e17701"); } }
	public static Color PineGreen { get { return ColorTranslator.FromHTML("#0a481e"); } }
	public static Color Charcoal { get { return ColorTranslator.FromHTML("#343837"); } }
	public static Color BabyPink { get { return ColorTranslator.FromHTML("#ffb7ce"); } }
	public static Color Cornflower { get { return ColorTranslator.FromHTML("#6a79f7"); } }
	public static Color BlueViolet { get { return ColorTranslator.FromHTML("#5d06e9"); } }
	public static Color Chocolate { get { return ColorTranslator.FromHTML("#3d1c02"); } }
	public static Color GreyishGreen { get { return ColorTranslator.FromHTML("#82a67d"); } }
	public static Color Scarlet { get { return ColorTranslator.FromHTML("#be0119"); } }
	public static Color GreenYellow { get { return ColorTranslator.FromHTML("#c9ff27"); } }
	public static Color DarkOlive { get { return ColorTranslator.FromHTML("#373e02"); } }
	public static Color Sienna { get { return ColorTranslator.FromHTML("#a9561e"); } }
	public static Color PastelPurple { get { return ColorTranslator.FromHTML("#caa0ff"); } }
	public static Color Terracotta { get { return ColorTranslator.FromHTML("#ca6641"); } }
	public static Color AquaBlue { get { return ColorTranslator.FromHTML("#02d8e9"); } }
	public static Color SageGreen { get { return ColorTranslator.FromHTML("#88b378"); } }
	public static Color BloodRed { get { return ColorTranslator.FromHTML("#980002"); } }
	public static Color DeepPink { get { return ColorTranslator.FromHTML("#cb0162"); } }
	public static Color Grass { get { return ColorTranslator.FromHTML("#5cac2d"); } }
	public static Color Moss { get { return ColorTranslator.FromHTML("#769958"); } }
	public static Color PastelBlue { get { return ColorTranslator.FromHTML("#a2bffe"); } }
	public static Color BluishGreen { get { return ColorTranslator.FromHTML("#10a674"); } }
	public static Color GreenBlue { get { return ColorTranslator.FromHTML("#06b48b"); } }
	public static Color DarkTan { get { return ColorTranslator.FromHTML("#af884a"); } }
	public static Color GreenishBlue { get { return ColorTranslator.FromHTML("#0b8b87"); } }
	public static Color PaleOrange { get { return ColorTranslator.FromHTML("#ffa756"); } }
	public static Color Vomit { get { return ColorTranslator.FromHTML("#a2a415"); } }
	public static Color ForrestGreen { get { return ColorTranslator.FromHTML("#154406"); } }
	public static Color DarkLavender { get { return ColorTranslator.FromHTML("#856798"); } }
	public static Color DarkViolet { get { return ColorTranslator.FromHTML("#34013f"); } }
	public static Color PurpleBlue { get { return ColorTranslator.FromHTML("#632de9"); } }
	public static Color DarkCyan { get { return ColorTranslator.FromHTML("#0a888a"); } }
	public static Color OliveDrab { get { return ColorTranslator.FromHTML("#6f7632"); } }
	public static Color Pinkish { get { return ColorTranslator.FromHTML("#d46a7e"); } }
	public static Color Cobalt { get { return ColorTranslator.FromHTML("#1e488f"); } }
	public static Color NeonPurple { get { return ColorTranslator.FromHTML("#bc13fe"); } }
	public static Color LightTurquoise { get { return ColorTranslator.FromHTML("#7ef4cc"); } }
	public static Color AppleGreen { get { return ColorTranslator.FromHTML("#76cd26"); } }
	public static Color DullGreen { get { return ColorTranslator.FromHTML("#74a662"); } }
	public static Color Wine { get { return ColorTranslator.FromHTML("#80013f"); } }
	public static Color PowderBlue { get { return ColorTranslator.FromHTML("#b1d1fc"); } }
	public static Color OffWhite { get { return ColorTranslator.FromHTML("#ffffe4"); } }
	public static Color ElectricBlue { get { return ColorTranslator.FromHTML("#0652ff"); } }
	public static Color DarkTurquoise { get { return ColorTranslator.FromHTML("#045c5a"); } }
	public static Color BluePurple { get { return ColorTranslator.FromHTML("#5729ce"); } }
	public static Color Azure { get { return ColorTranslator.FromHTML("#069af3"); } }
	public static Color BrightRed { get { return ColorTranslator.FromHTML("#ff000d"); } }
	public static Color PinkishRed { get { return ColorTranslator.FromHTML("#f10c45"); } }
	public static Color CornflowerBlue { get { return ColorTranslator.FromHTML("#5170d7"); } }
	public static Color LightOlive { get { return ColorTranslator.FromHTML("#acbf69"); } }
	public static Color Grape { get { return ColorTranslator.FromHTML("#6c3461"); } }
	public static Color GreyishBlue { get { return ColorTranslator.FromHTML("#5e819d"); } }
	public static Color PurplishBlue { get { return ColorTranslator.FromHTML("#601ef9"); } }
	public static Color YellowishGreen { get { return ColorTranslator.FromHTML("#b0dd16"); } }
	public static Color GreenishYellow { get { return ColorTranslator.FromHTML("#cdfd02"); } }
	public static Color MediumBlue { get { return ColorTranslator.FromHTML("#2c6fbb"); } }
	public static Color DustyRose { get { return ColorTranslator.FromHTML("#c0737a"); } }
	public static Color LightViolet { get { return ColorTranslator.FromHTML("#d6b4fc"); } }
	public static Color MidnightBlue { get { return ColorTranslator.FromHTML("#020035"); } }
	public static Color BluishPurple { get { return ColorTranslator.FromHTML("#703be7"); } }
	public static Color RedOrange { get { return ColorTranslator.FromHTML("#fd3c06"); } }
	public static Color DarkMagenta { get { return ColorTranslator.FromHTML("#960056"); } }
	public static Color Greenish { get { return ColorTranslator.FromHTML("#40a368"); } }
	public static Color OceanBlue { get { return ColorTranslator.FromHTML("#03719c"); } }
	public static Color Coral { get { return ColorTranslator.FromHTML("#fc5a50"); } }
	public static Color Cream { get { return ColorTranslator.FromHTML("#ffffc2"); } }
	public static Color ReddishBrown { get { return ColorTranslator.FromHTML("#7f2b0a"); } }
	public static Color BurntSienna { get { return ColorTranslator.FromHTML("#b04e0f"); } }
	public static Color Brick { get { return ColorTranslator.FromHTML("#a03623"); } }
	public static Color Sage { get { return ColorTranslator.FromHTML("#87ae73"); } }
	public static Color GreyGreen { get { return ColorTranslator.FromHTML("#789b73"); } }
	public static Color White { get { return ColorTranslator.FromHTML("#ffffff"); } }
	public static Color RobinSEggBlue { get { return ColorTranslator.FromHTML("#98eff9"); } }
	public static Color MossGreen { get { return ColorTranslator.FromHTML("#658b38"); } }
	public static Color SteelBlue { get { return ColorTranslator.FromHTML("#5a7d9a"); } }
	public static Color Eggplant { get { return ColorTranslator.FromHTML("#380835"); } }
	public static Color LightYellow { get { return ColorTranslator.FromHTML("#fffe7a"); } }
	public static Color LeafGreen { get { return ColorTranslator.FromHTML("#5ca904"); } }
	public static Color LightGrey { get { return ColorTranslator.FromHTML("#d8dcd6"); } }
	public static Color Puke { get { return ColorTranslator.FromHTML("#a5a502"); } }
	public static Color PinkishPurple { get { return ColorTranslator.FromHTML("#d648d7"); } }
	public static Color SeaBlue { get { return ColorTranslator.FromHTML("#047495"); } }
	public static Color PalePurple { get { return ColorTranslator.FromHTML("#b790d4"); } }
	public static Color SlateBlue { get { return ColorTranslator.FromHTML("#5b7c99"); } }
	public static Color BlueGrey { get { return ColorTranslator.FromHTML("#607c8e"); } }
	public static Color HunterGreen { get { return ColorTranslator.FromHTML("#0b4008"); } }
	public static Color Fuchsia { get { return ColorTranslator.FromHTML("#ed0dd9"); } }
	public static Color Crimson { get { return ColorTranslator.FromHTML("#8c000f"); } }
	public static Color PaleYellow { get { return ColorTranslator.FromHTML("#ffff84"); } }
	public static Color Ochre { get { return ColorTranslator.FromHTML("#bf9005"); } }
	public static Color MustardYellow { get { return ColorTranslator.FromHTML("#d2bd0a"); } }
	public static Color LightRed { get { return ColorTranslator.FromHTML("#ff474c"); } }
	public static Color Cerulean { get { return ColorTranslator.FromHTML("#0485d1"); } }
	public static Color PalePink { get { return ColorTranslator.FromHTML("#ffcfdc"); } }
	public static Color DeepBlue { get { return ColorTranslator.FromHTML("#040273"); } }
	public static Color Rust { get { return ColorTranslator.FromHTML("#a83c09"); } }
	public static Color LightTeal { get { return ColorTranslator.FromHTML("#90e4c1"); } }
	public static Color Slate { get { return ColorTranslator.FromHTML("#516572"); } }
	public static Color Goldenrod { get { return ColorTranslator.FromHTML("#fac205"); } }
	public static Color DarkYellow { get { return ColorTranslator.FromHTML("#d5b60a"); } }
	public static Color DarkGrey { get { return ColorTranslator.FromHTML("#363737"); } }
	public static Color ArmyGreen { get { return ColorTranslator.FromHTML("#4b5d16"); } }
	public static Color GreyBlue { get { return ColorTranslator.FromHTML("#6b8ba4"); } }
	public static Color Seafoam { get { return ColorTranslator.FromHTML("#80f9ad"); } }
	public static Color Puce { get { return ColorTranslator.FromHTML("#a57e52"); } }
	public static Color SpringGreen { get { return ColorTranslator.FromHTML("#a9f971"); } }
	public static Color DarkOrange { get { return ColorTranslator.FromHTML("#c65102"); } }
	public static Color Sand { get { return ColorTranslator.FromHTML("#e2ca76"); } }
	public static Color PastelGreen { get { return ColorTranslator.FromHTML("#b0ff9d"); } }
	public static Color Mint { get { return ColorTranslator.FromHTML("#9ffeb0"); } }
	public static Color LightOrange { get { return ColorTranslator.FromHTML("#fdaa48"); } }
	public static Color BrightPink { get { return ColorTranslator.FromHTML("#fe01b1"); } }
	public static Color Chartreuse { get { return ColorTranslator.FromHTML("#c1f80a"); } }
	public static Color DeepPurple { get { return ColorTranslator.FromHTML("#36013f"); } }
	public static Color DarkBrown { get { return ColorTranslator.FromHTML("#341c02"); } }
	public static Color Taupe { get { return ColorTranslator.FromHTML("#b9a281"); } }
	public static Color PeaGreen { get { return ColorTranslator.FromHTML("#8eab12"); } }
	public static Color PukeGreen { get { return ColorTranslator.FromHTML("#9aae07"); } }
	public static Color KellyGreen { get { return ColorTranslator.FromHTML("#02ab2e"); } }
	public static Color SeafoamGreen { get { return ColorTranslator.FromHTML("#7af9ab"); } }
	public static Color BlueGreen { get { return ColorTranslator.FromHTML("#137e6d"); } }
	public static Color Khaki { get { return ColorTranslator.FromHTML("#aaa662"); } }
	public static Color Burgundy { get { return ColorTranslator.FromHTML("#610023"); } }
	public static Color DarkTeal { get { return ColorTranslator.FromHTML("#014d4e"); } }
	public static Color BrickRed { get { return ColorTranslator.FromHTML("#8f1402"); } }
	public static Color RoyalPurple { get { return ColorTranslator.FromHTML("#4b006e"); } }
	public static Color Plum { get { return ColorTranslator.FromHTML("#580f41"); } }
	public static Color MintGreen { get { return ColorTranslator.FromHTML("#8fff9f"); } }
	public static Color Gold { get { return ColorTranslator.FromHTML("#dbb40c"); } }
	public static Color BabyBlue { get { return ColorTranslator.FromHTML("#a2cffe"); } }
	public static Color YellowGreen { get { return ColorTranslator.FromHTML("#c0fb2d"); } }
	public static Color BrightPurple { get { return ColorTranslator.FromHTML("#be03fd"); } }
	public static Color DarkRed { get { return ColorTranslator.FromHTML("#840000"); } }
	public static Color PaleBlue { get { return ColorTranslator.FromHTML("#d0fefe"); } }
	public static Color GrassGreen { get { return ColorTranslator.FromHTML("#3f9b0b"); } }
	public static Color Navy { get { return ColorTranslator.FromHTML("#01153e"); } }
	public static Color Aquamarine { get { return ColorTranslator.FromHTML("#04d8b2"); } }
	public static Color BurntOrange { get { return ColorTranslator.FromHTML("#c04e01"); } }
	public static Color NeonGreen { get { return ColorTranslator.FromHTML("#0cff0c"); } }
	public static Color BrightBlue { get { return ColorTranslator.FromHTML("#0165fc"); } }
	public static Color Rose { get { return ColorTranslator.FromHTML("#cf6275"); } }
	public static Color LightPink { get { return ColorTranslator.FromHTML("#ffd1df"); } }
	public static Color Mustard { get { return ColorTranslator.FromHTML("#ceb301"); } }
	public static Color Indigo { get { return ColorTranslator.FromHTML("#380282"); } }
	public static Color Lime { get { return ColorTranslator.FromHTML("#aaff32"); } }
	public static Color SeaGreen { get { return ColorTranslator.FromHTML("#53fca1"); } }
	public static Color Periwinkle { get { return ColorTranslator.FromHTML("#8e82fe"); } }
	public static Color DarkPink { get { return ColorTranslator.FromHTML("#cb416b"); } }
	public static Color OliveGreen { get { return ColorTranslator.FromHTML("#677a04"); } }
	public static Color Peach { get { return ColorTranslator.FromHTML("#ffb07c"); } }
	public static Color PaleGreen { get { return ColorTranslator.FromHTML("#c7fdb5"); } }
	public static Color LightBrown { get { return ColorTranslator.FromHTML("#ad8150"); } }
	public static Color HotPink { get { return ColorTranslator.FromHTML("#ff028d"); } }
	public static Color Black { get { return ColorTranslator.FromHTML("#000000"); } }
	public static Color Lilac { get { return ColorTranslator.FromHTML("#cea2fd"); } }
	public static Color NavyBlue { get { return ColorTranslator.FromHTML("#001146"); } }
	public static Color RoyalBlue { get { return ColorTranslator.FromHTML("#0504aa"); } }
	public static Color Beige { get { return ColorTranslator.FromHTML("#e6daa6"); } }
	public static Color Salmon { get { return ColorTranslator.FromHTML("#ff796c"); } }
	public static Color Olive { get { return ColorTranslator.FromHTML("#6e750e"); } }
	public static Color Maroon { get { return ColorTranslator.FromHTML("#650021"); } }
	public static Color BrightGreen { get { return ColorTranslator.FromHTML("#01ff07"); } }
	public static Color DarkPurple { get { return ColorTranslator.FromHTML("#35063e"); } }
	public static Color Mauve { get { return ColorTranslator.FromHTML("#ae7181"); } }
	public static Color ForestGreen { get { return ColorTranslator.FromHTML("#06470c"); } }
	public static Color Aqua { get { return ColorTranslator.FromHTML("#13eac9"); } }
	public static Color Cyan { get { return ColorTranslator.FromHTML("#00ffff"); } }
	public static Color Tan { get { return ColorTranslator.FromHTML("#d1b26f"); } }
	public static Color DarkBlue { get { return ColorTranslator.FromHTML("#00035b"); } }
	public static Color Lavender { get { return ColorTranslator.FromHTML("#c79fef"); } }
	public static Color Turquoise { get { return ColorTranslator.FromHTML("#06c2ac"); } }
	public static Color DarkGreen { get { return ColorTranslator.FromHTML("#033500"); } }
	public static Color Violet { get { return ColorTranslator.FromHTML("#9a0eea"); } }
	public static Color LightPurple { get { return ColorTranslator.FromHTML("#bf77f6"); } }
	public static Color LimeGreen { get { return ColorTranslator.FromHTML("#89fe05"); } }
	public static Color Grey { get { return ColorTranslator.FromHTML("#929591"); } }
	public static Color SkyBlue { get { return ColorTranslator.FromHTML("#75bbfd"); } }
	public static Color Yellow { get { return ColorTranslator.FromHTML("#ffff14"); } }
	public static Color Magenta { get { return ColorTranslator.FromHTML("#c20078"); } }
	public static Color LightGreen { get { return ColorTranslator.FromHTML("#96f97b"); } }
	public static Color Orange { get { return ColorTranslator.FromHTML("#f97306"); } }
	public static Color Teal { get { return ColorTranslator.FromHTML("#029386"); } }
	public static Color LightBlue { get { return ColorTranslator.FromHTML("#95d0fc"); } }
	public static Color Red { get { return ColorTranslator.FromHTML("#e50000"); } }
	public static Color Brown { get { return ColorTranslator.FromHTML("#653700"); } }
	public static Color Pink { get { return ColorTranslator.FromHTML("#ff81c0"); } }
	public static Color Blue { get { return ColorTranslator.FromHTML("#0343df"); } }
	public static Color Green { get { return ColorTranslator.FromHTML("#15b01a"); } }
	public static Color Purple { get { return ColorTranslator.FromHTML("#7e1e9c"); } }
}
